// BurgerBuilder
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const INITIATE = 'INITIATE';
export const FETCH_INITIAL_DATA_FAILED = 'FETCH_INITIAL_DATA_FAILED';

// Purchase Burger
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';

// Auth
export const FETCH_USER = 'FETCH_USER';